### ISSUE TITLE
Jedi12 example robot

### ISSUE THREAD

**Issue by iw6dgm** [troglobit/crobots#1]
Hello,

Would you be so kind to re-instate Jedi12 original header (comments) or at least add a comment with the link to its original source https://crobots.deepthought.it/home.php?page=src2html&id=4x1a3j

Thank you

**Comment by troglobit** [comment]
Thanks for the heads-up!  When I initially created my fork of CRobots, I based on the Linux port by https://github.com/pabloalgar/crobots/, which included your Robot without attribution.  Sorry about that.

**Comment by iw6dgm** [comment]
> Thanks for the heads-up! When I initially created my fork of CRobots, I based on the Linux port by https://github.com/pabloalgar/crobots/, which included your Robot without attribution. Sorry about that.

Thank you!
No problem.

I will notify that repo too :)

Cheers
